name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Build static site
        run: |
          mkdir -p ./public
          echo "<!DOCTYPE html><html><head><title>ML-Health</title></head><body><h1>Welcome to ML-Health</h1><p>Our research group focuses on machine learning for healthcare, specifically neurodegenerative diseases.</p></body></html>" > ./public/index.html

      - name: Deploy to GitHub Pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./public

    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
